id: P004309
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24471
  title: བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་མཐའ་དཔྱོད།
  author: ''
  volumes:
    00f4172b151741c687c5505ea6864326:
      image_group_id: I1KG24493
      title: ''
      volume_number: 1
      total_pages: 938
